// Translation strings: English (fallback) + Swedish.
//
// Covers the global chrome (sidebar, topbar, popovers) and the home page —
// see js/lib/i18n.js for how these are looked up. Other views still have
// their user-facing text hardcoded in English/Swedish directly; this file
// grows as more views get wired up to t().

export const STRINGS = {
  en: {
    // ---- global chrome ----
    "nav.home": "Home",
    "nav.library": "Library",
    "nav.create": "Create",
    "nav.progress": "Progress",
    "nav.parent": "Parent / teacher",
    "nav.settings": "Settings",
    "nav.mainMenu": "Main menu",

    "streak.days": "{n}-day streak",
    "streak.none": "No streak yet",

    "theme.group": "Theme",
    "theme.light": "Light",
    "theme.system": "Match my device",
    "theme.dark": "Dark",

    "topbar.notifications": "Notifications",
    "topbar.account": "Account",
    "notif.dueReviewOne": "1 question waiting for review",
    "notif.dueReviewMany": "{n} questions waiting for review",
    "notif.dueReviewBody": "Questions from sets you've already studied are ready for another look.",
    "notif.dueSinceToday": "Due today",
    "notif.dueSinceDayOne": "Due since 1 day ago",
    "notif.dueSinceDayMany": "Due since {n} days ago",
    "notif.reviewNow": "Review now",
    "notif.examToday": "The exam is today",
    "notif.examTomorrow": "The exam is tomorrow",
    "notif.examInDays": "The exam is in {n} days",
    "notif.examBody": "Make sure your review sets are up to date before then.",
    "notif.viewExam": "View",
    "notif.none": "No new notifications.",
    "notif.noneRead": "Nothing read yet.",
    "notif.panelTitle": "Notifications",
    "notif.tabUnread": "Unread",
    "notif.tabRead": "Read",
    "notif.markRead": "Mark as read",
    "account.signedInAs": "Signed in as {email}",
    "account.settings": "Settings",
    "account.signOut": "Sign out",
    "account.signOutDone": "Signed out — local mode",
    "account.signIn": "Sign in / create account",

    "settings.language": "Language",
    "settings.langUpdated": "Language updated",
    "common.loading": "Loading…",
    "common.error": "Something went wrong",
    "common.backToMenu": "Back to menu",

    // ---- home page ----
    "greeting.morning": "Good morning",
    "greeting.afternoon": "Good afternoon",
    "greeting.evening": "Good evening",
    "menu.hintLive": "Pick something to study, or make a new set.",
    "menu.hintDemo": "Running in demo mode — see Settings for how to turn on live mode.",
    "menu.newSet": "New set",
    "menu.pageTitle": "Menu",

    "dash.noResults": "No results yet",
    "dash.overallMastery": "Overall mastery",
    "dash.startStudying": "Start studying",
    "dash.heroHintEmpty": "Finish a session and your level shows up here.",
    "dash.heroHint": "{topics} tracked · {sessions} done",
    "dash.topic": "1 topic",
    "dash.topics": "{n} topics",
    "dash.session": "1 session",
    "dash.sessions": "{n} sessions",
    "dash.dayStreak": "day streak",
    "dash.daysStreak": "days streak",
    "dash.streakEmpty": "Study today to start a streak",
    "dash.dueNow": "Due now — tap to review",
    "dash.dueForReview": "Due for review",

    "today.continue": "Continue where you left off",
    "today.progress": "{title} · {n} of {total} answered",

    "sets.heading": "Your sets",
    "sets.searchPlaceholder": "Search sets…",
    "sets.sortNewest": "Newest",
    "sets.sortAZ": "A–Z",
    "sets.sortWeakest": "Weakest",
    "sets.tabAssignments": "Assignments",
    "sets.tabTests": "Tests",
    "sets.assignmentsNoun": "assignments",
    "sets.testsNoun": "tests",
    "sets.chipAll": "All",
    "sets.generalSubject": "General",
    "sets.newAssignment": "New assignment",
    "sets.newTest": "New test",
    "sets.inProgress": "In progress",
    "sets.answeredProgress": "{answered} of {total} answered",
    "sets.questionCount": "1 question",
    "sets.questionsCount": "{n} questions",
    "sets.doneTimes": " · done {n}×",
    "sets.setCount": "1 set",
    "sets.setsCount": "{n} sets",
    "sets.noMatch": "No {tab} match “{query}”. ",
    "sets.matchSwitch": "{n} {tab} match — switch to {target}",

    "empty.libraryTitle": "Your library is empty",
    "empty.libraryBody": "Start with ready-made sets from the library — or make your own from your notes, a PDF, a photo, or just a topic.",
    "empty.noAssignments": "No assignments yet",
    "empty.noTests": "No tests yet",
    "empty.assignmentBody": "Make one from your notes, a PDF, a photo, or just a topic.",
    "empty.testBody": "Create one the same way — just mark it as a test.",
    "empty.openLibrary": "Open the practice library",
    "empty.tryDemo": "Try a demo",
    "empty.demoAdded": "Demo sets added",
    "empty.demoFailed": "Couldn't load the demo sets",

    "cardmenu.examMode": "Start in exam mode",
    "cardmenu.rename": "Rename",
    "cardmenu.editQuestions": "Edit questions",
    "cardmenu.duplicate": "Duplicate",
    "cardmenu.delete": "Delete",
    "cardmenu.renamePrompt": "Rename this set:",
    "cardmenu.renameNeedsName": "A set needs a name",
    "cardmenu.renamed": "Renamed",
    "cardmenu.copiedAs": "Copied as “{title}”",
    "cardmenu.deleteConfirm": "Delete “{title}”?{extra}\n\nThis can't be undone.",
    "cardmenu.deleteExtra": "\n\nThis also removes 1 recorded attempt from your history.",
    "cardmenu.deleteExtraMany": "\n\nThis also removes {n} recorded attempts from your history.",
    "cardmenu.deleted": "Deleted",

    "examcard.title": "Next exam",
    "examcard.date": "Date",
    "examcard.about": "What's it about? (optional)",
    "examcard.aboutPlaceholder": "e.g. National test in maths",
    "examcard.save": "Save",
    "examcard.cancel": "Cancel",
    "examcard.change": "Change",
    "examcard.pickDateFirst": "Pick a date first",
    "examcard.past": "Already happened",
    "examcard.today": "Today",
    "examcard.tomorrow": "Tomorrow",
    "examcard.daysLeft": "{n} days left",

    "tips.heading": "Today's study tip",
    "tips.0": "Test yourself before re-reading a chapter — actively recalling sticks better than just reading it again.",
    "tips.1": "Short, repeated sessions beat long cram marathons. Do 25 focused minutes, then take a real break.",
    "tips.2": "Mix several subjects instead of grinding one at a time — your brain learns better from switching than from repeating the same thing for hours.",
    "tips.3": "Explain what you just learned out loud, as if teaching someone else. If you can't explain it simply, you don't quite have it yet.",
    "tips.4": "Study the hardest part first, while you're still fresh and focused.",
    "tips.5": "Sleep is part of learning — your brain consolidates memories while you sleep, so a late review session isn't wasted.",
    "tips.6": "Old mistakes are worth gold. Go over what you got wrong last time before starting a new set.",

    // ---- study session ----
    "session.setGone": "That set no longer exists.",
    "session.setEmpty": "That set has no questions yet.",
    "session.questionsGone": "These questions are no longer available.",
    "session.resultGone": "That result is no longer available.",
    "session.noImportedSets": "No imported sets for this subject yet.",
    "session.notFoundTitle": "Not found",
    "session.nothingToStudy": "Nothing to study here",
    "session.reviewTitle": "Review",
    "session.reviewSessionTitle": "Review session",
    "session.nothingDue": "Nothing due right now",
    "session.nothingDueBody": "Spaced repetition brings questions back just before you'd forget them. Come back tomorrow, or study a set to add more.",
    "session.practiceTitle": "Practice",
    "session.nothingToPractice": "Nothing to practise",
    "session.nothingToPracticeBody": "You got everything right in that session.",
    "session.mixedTitle": "Mixed – {subject}",
    "session.nationalTest": "National test",
    "session.next": "Next",
    "session.finish": "Finish",
    "session.skip": "Skip for now",
    "session.exit": "Exit",
    "session.timeUp": "Time's up — your answers were submitted automatically.",
    "session.skippedAnnounce": "Skipped. You'll see this one again at the end.",
    "session.questionAnnounce": "Question {n} of {total}.",
    "session.progressLabel": "Question {n} of {total} · {done} answered",
    "session.progressSkipped": " · {n} skipped",
    "session.exitConfirm": "Leave this session?\n\nYour progress is saved — you can pick up where you left off.",
    "session.resumeTitle": "Pick up where you left off?",
    "session.resumeBodyOne": "You answered {done} of {total} question last time",
    "session.resumeBodyMany": "You answered {done} of {total} questions last time",
    "session.resumeMore": " — {n} to go.",
    "session.resumeReady": ", so you're ready to finish.",
    "session.continue": "Continue",
    "session.startOver": "Start over",
    "session.shortcutsTitle": "Keyboard shortcuts",
    "session.shortcutPickMc": "Pick a multiple-choice answer",
    "session.shortcutCheck": "Check your answer, then move on",
    "session.shortcutNext": "Next question",
    "session.shortcutSkip": "Skip for now",
    "session.shortcutFlip": "Flip a flashcard",
    "session.shortcutShow": "Show this list",
    "session.close": "Close",
    "session.needHint": "Need a hint?",
    "session.hideTutor": "Hide tutor",
    "session.testModeWarn": "Test mode: one attempt per question and no hints. The tutor will go through it with you afterwards.",
    "session.kbdHintPre": "Tip: press ",
    "session.kbdHintPost": " for keyboard shortcuts.",
    "session.badgeReview": "Review",
    "session.badgePractice": "Practice",
    "session.badgeExamMode": "Exam mode",
    "session.badgeAssignment": "Assignment",
    "session.badgeTest": "Test",

    // ---- question renderers ----
    "q.listenQuestion": "Read the question aloud",
    "q.listen": "Listen",
    "q.checkAnswer": "Check answer",
    "q.answerRecorded": "Answer recorded.",
    "q.correctBang": "Correct!",
    "q.retryHint": "Still not right. Read the tutor's hint, then pick again — or reveal the answer below.",
    "q.tryAgain": "Not quite — have another go.",
    "q.revealAnswer": "Reveal answer & continue",
    "q.answerIs": "The answer is {letter}.",
    "q.wrongChoiceNote": "I chose \"{choice}\" and it's wrong. Can you help me see why?",
    "q.celebrateChoice": "I picked the right one!",
    "q.yourAnswerPlaceholder": "Type your answer…",
    "q.submitAnswer": "Submit answer",
    "q.submitting": "Submitting…",
    "q.checking": "Checking…",
    "q.modelAnswerLabel": "Model answer:",
    "q.celebrateText": "I think I got that one.",
    "q.wroteNote": "Here's what I wrote: \"{answer}\". What am I missing?",
    "q.markedCorrect": "Marked as correct. Have a look at the model answer anyway — it's easy to miss a bit.",
    "q.disagree": "Disagree with the marking? ",
    "q.iThinkRight": "I think my answer was right",
    "q.rateAgain": "Again",
    "q.rateHard": "Hard",
    "q.rateGood": "Good",
    "q.rateEasy": "Easy",
    "q.forgotNote": "I couldn't remember this one. Can you help it stick?",
    "q.rememberedCelebrate": "Remembered it!",
    "q.tapToFlip": "Tap the card to flip, or press Space.",
    "q.workHerePlain": "Work it out here.",
    "q.workHereTutor": "Work it out here — the tutor on the right will help.",
    "q.showStep": "Show a step",
    "q.doneShowAnswer": "I'm done — show the answer",
    "q.revealStepNote": "I've revealed step {n}. Can you nudge me toward the next bit?",
    "q.leftBlank": "Left blank.",
    "q.fullSolutionLabel": "Full solution:",
    "q.reasoningCheck": "Did your reasoning get there?",
    "q.hadIt": "Yes, I had it",
    "q.notQuite": "Not quite",
    "q.heuristicNoModel": "Compare your answer with the model answer below.",
    "q.heuristicGood": "That covers the key ideas — check the details below.",
    "q.heuristicMissing": "This looks like it's missing some of the key ideas. Compare it with the model answer below.",

    // ---- results screen ----
    "results.noResults": "No results to show",
    "results.genericSession": "Session",
    "results.great": "Great work",
    "results.niceEffort": "Nice effort",
    "results.examModeSuffix": " · exam mode",
    "results.testSuffix": " · test",
    "results.limitSuffix": " (limit {n} min)",
    "results.timedOut": "Time ran out — this was submitted automatically.",
    "results.topicMastery": "Topic mastery",
    "results.worthAnotherLook": "Worth another look",
    "results.practiseOne": "Practise this now",
    "results.practiseMany": "Practise these {n} now",
    "results.tutorSatOut": "The tutor sat out the test — it'll work through these with you now.",
    "results.reviewAgain": "Review again",
    "results.tryAgain": "Try again",
    "results.seeProgress": "See progress",
    "results.pageTitle": "Results",
    "results.correctCount": "{c} / {n} correct",
    "results.tookHours": "Took {h}h {m}m",
    "results.tookSecs": "Took {n}s",
    "results.tookMin": "Took {n} min",
    "results.tookMin30": "Took {n} min 30s",
    "results.gradeEyebrow": "Estimated grade",
    "results.gradeFirstTime": "Your first result on this one — nice benchmark to beat next time.",
    "results.gradeUpFrom": "Up from {letter} — your best on this yet.",
    "results.gradeMatchesBest": "Matches your best on this so far.",
    "results.gradeBestSoFar": "Your best on this is still {letter} — worth another go.",

    // ---- spaced repetition due labels ----
    "srs.dueNow": "due now",
    "srs.tomorrow": "tomorrow",
    "srs.inDays": "in {n} days",
    "srs.inWeeks": "in {n} wk",
    "srs.inMonths": "in {n} mo",

    // ---- progress page ----
    "progress.title": "Your progress",
    "progress.pageTitle": "Progress",
    "progress.studyStreak": "Study streak",
    "progress.studiedDays": "1 day studied",
    "progress.studiedDaysMany": "{n} days studied",
    "progress.sessionsOne": "1 session completed",
    "progress.sessionsMany": "{n} sessions completed",
    "progress.masteryBySubject": "Mastery by subject",
    "progress.gradeExplain": "The letter is an estimated level (E–A) based on how you've performed in your exercises — not an actual grade.",
    "progress.gradeTooltip": "Estimated level {letter} based on your answers — not an actual grade",
    "progress.noMasteryYet": "Finish a session to start building mastery scores. Weakest topics show first.",
    "progress.dueForReview": "Due for review",
    "progress.reviewToday": "Review today",
    "progress.reviewTodayExplain": "“Review today” practises just these questions, pulled from every set.",
    "progress.moreItems": "+ {n} more",
    "progress.nothingDue": "Nothing due right now. Spaced repetition brings questions back just before you'd forget them.",

    // ---- create flow ----
    "create.title": "New study set",
    "create.pageTitle": "New set",
    "create.stepSource": "Source",
    "create.stepMaterial": "Material",
    "create.stepReview": "Review",
    "create.sourceQuestion": "Where should the questions come from?",
    "create.sourcePaste": "Paste text",
    "create.sourcePasteDesc": "Notes, an article, a chapter",
    "create.sourcePdf": "Upload PDF",
    "create.sourcePdfDesc": "A worksheet, textbook page, or ZIP",
    "create.sourcePhoto": "Upload photo",
    "create.sourcePhotoDesc": "A picture of a page or board",
    "create.sourceTopic": "Just a topic",
    "create.sourceTopicDesc": "e.g. “Grade 5 fractions”",
    "create.sourceNational": "National test",
    "create.sourceNationalDesc": "Practise for national tests",
    "create.needsServerPre": "Generating needs the tutor server (see ",
    "create.needsServerPost": ") — or explore the sample set on the menu for now.",
    "create.reading": "Reading…",
    "create.zipExtracted": "Extracted text from {pdfCount} of {totalPdfCount} {noun} in \"{name}\"{audioNote}.",
    "create.pdfFile": "PDF file",
    "create.pdfFiles": "PDF files",
    "create.audioSkippedOne": " ({n} audio file skipped)",
    "create.audioSkippedMany": " ({n} audio files skipped)",
    "create.pdfExtracted": "Extracted {n} characters from \"{name}\".",
    "create.readError": "Could not read that file.",
    "create.pdfOrZipLabel": "PDF or ZIP file",
    "create.importedSetsOne": "1 imported set for this subject:",
    "create.importedSetsMany": "{n} imported sets for this subject:",
    "create.setQuestionsOne": "→ {title} (1 question)",
    "create.setQuestionsMany": "→ {title} ({n} questions)",
    "create.mixAllYears": "Mix all years — number of questions:",
    "create.startMix": "Start mix",
    "create.exampleBadge": "Example",
    "create.externalBadge": "External site",
    "create.getMaterial": "Get exam material ↗",
    "create.limitedExplain": "Real past tests in this subject contain copyrighted texts, so only example questions are freely published — the link shows those. Full past tests must be requested from Skolverket as a \"request for a public record\".",
    "create.externalExplain": "Opens a page with past tests at a university — get what you want to practise on (PDF, ZIP, or whatever they offer), then upload or paste it here.",
    "create.levelPlaceholder": "Choose level…",
    "create.levelLabel": "Level",
    "create.subjectPlaceholder": "Choose subject…",
    "create.subjectLabel": "Subject",
    "create.typeLabel": "Type",
    "create.pasteExcerptPlaceholder": "Paste an excerpt from the test here (optional if you upload the file below)…",
    "create.pasteTextLabel": "Paste text",
    "create.pastePlaceholder": "Paste your notes or reading here…",
    "create.studyMaterialLabel": "Study material",
    "create.topicPlaceholder": "e.g. The water cycle, Grade 4",
    "create.topicLabel": "Topic",
    "create.yearAgePlaceholder": "e.g. Year 8 / age 13 (optional)",
    "create.yearAgeLabel": "Year / age level",
    "create.photoLabel": "Photo",
    "create.loaded": "Loaded \"{name}\".",
    "create.assignmentOption": "Assignment (practice)",
    "create.testOption": "Test (quiz)",
    "create.howManyQuestions": "How many questions",
    "create.preferFlashcards": "Prefer flashcards",
    "create.generate": "Generate questions",
    "create.addMaterialFirst": "Add some material or a topic first.",
    "create.generationFailed": "Generation failed. Try again or simplify the material.",
    "create.back": "Back",
    "create.writingQuestions": "Writing your questions…",
    "create.usuallyTakes": "This usually takes 10–30 seconds.",
    "create.setTitleLabel": "Title",
    "create.questionCountOne": "1 question · edit anything below, then save.",
    "create.questionCountMany": "{n} questions · edit anything below, then save.",
    "create.addQuestion": "+ question",
    "create.saveSet": "Save set",
    "create.needQuestion": "Add at least one question.",
    "create.needName": "Give the set a name.",
    "create.saved": "Saved!",
    "create.subjectLocked": "Locked to national-test subject",

    // ---- edit set ----
    "edit.title": "Edit set",
    "edit.pageTitle": "Edit — {title}",
    "edit.setName": "Give the set a name",
    "edit.needQuestion": "A set needs at least one question",
    "edit.saved": "Saved",
    "edit.cancel": "Cancel",
    "edit.saveChanges": "Save changes",
    "edit.questionCountOne": "1 question",
    "edit.questionCountMany": "{n} questions",

    // ---- question editor ----
    "qedit.mc": "Multiple choice",
    "qedit.text": "Short answer",
    "qedit.flashcard": "Flashcard",
    "qedit.worked": "Worked problem",
    "qedit.noQuestions": "No questions yet — add one below.",
    "qedit.selectCorrect": "Select the radio button next to the correct choice.",
    "qedit.addChoice": "+ choice",
    "qedit.backOfCard": "Back of card",
    "qedit.modelAnswer": "Model answer",
    "qedit.topicPlaceholder": "topic",
    "qedit.deleteQuestion": "Delete question",
    "qedit.questionLabel": "Question",

    // ---- practice library ----
    "library.pageTitle": "Practice library",
    "library.loadFailed": "Couldn't load the library",
    "library.tryAgain": "Try again in a moment.",
    "library.toHome": "To home",
    "library.searchPlaceholder": "Search the library — subject, course or set…",
    "library.searchAria": "Search the practice library",
    "library.back": "Back",
    "library.noMatches": "No matches for \"{query}\". Try a subject, course, or grade.",
    "library.matchOne": "1 match",
    "library.matchMany": "{n} matches",
    "library.levelIntro": "Ready-made exercises you can start studying right away — no upload needed. Choose a level to see subjects.",
    "library.subjectIntro": "{level} — which subject do you want to study?",
    "library.addAll": "Add all ({n})",
    "library.addedOne": "Added 1 set",
    "library.addedMany": "Added {n} sets",
    "library.allAlready": "Everything was already in your library",
    "library.allAdded": "All sets added ✓",
    "library.study": "Study",
    "library.add": "Add",
    "library.added": "\"{title}\" added",
    "library.addFailed": "Couldn't add the set",
    "library.examMode": "Exam mode",
    "library.examModeTooltip": "Exam mode: timed, no hints, and the answer key only shows once you're done.",
    "library.questionsOne": "1 question",
    "library.questionsMany": "{n} questions",
    "library.levelAk7": "Grade 7",
    "library.levelAk8": "Grade 8",
    "library.levelAk9": "Grade 9",
    "library.levelGymnasiet": "Upper secondary school",

    // ---- sign in ----
    "login.signIn": "Sign in",
    "login.createAccount": "Create account",
    "login.needAccount": "Need an account? Create one",
    "login.haveAccount": "Already have an account? Sign in",
    "login.atLeast8": "At least 8 characters",
    "login.signedIn": "Signed in — syncing is on",
    "login.accountCreated": "Account created — syncing is on",
    "login.somethingWrong": "Something went wrong.",
    "login.email": "Email",
    "login.password": "Password",
    "login.pageHeading": "Account",
    "login.intro": "Sign in to sync your library and progress across devices. Fully optional — StudyBuddy keeps working locally if you skip this.",
    "login.backendDown": "The backend server isn't reachable right now — signing in won't work until it is.",
    "login.backToSettings": "Back to settings",
    "login.pageTitle": "Sign in",

    // ---- parent / teacher hub ----
    "parent.title": "Parent / teacher",
    "parent.requestFailed": "Request failed.",
    "parent.signInIntro": "Sign in to link accounts, assign work, and see progress.",
    "parent.studentsHeading": "Students you're linked to",
    "parent.noneYet": "None yet — redeem a student's invite code below.",
    "parent.unlinkConfirm": "Unlink {email}?",
    "parent.unlink": "Unlink",
    "parent.assignSet": "Assign a set",
    "parent.noOwnSets": "You don't have any sets of your own to assign yet — make one from the menu first.",
    "parent.assign": "Assign",
    "parent.assignedToast": "Assigned \"{title}\" to {email}",
    "parent.inviteCodePlaceholder": "e.g. AB12CD",
    "parent.link": "Link",
    "parent.linkedTo": "Linked to {email}",
    "parent.haveCode": "Have a student's invite code?",
    "parent.parentsHeading": "Parents / teachers linked to you",
    "parent.noParentsYet": "No one yet. Generate a code above and share it with a parent or teacher.",
    "parent.assignedHeading": "Assigned to you",
    "parent.couldntLoadAssigned": "Couldn't load assigned sets.",
    "parent.nothingWaiting": "Nothing waiting right now.",
    "parent.addToLibrary": "Add to my library",
    "parent.addedToLibrary": "Added \"{title}\" to your library",
    "parent.fromEmail": "from {email}",
    "parent.inviteStatus": "Generate a code and share it with a parent or teacher so they can link to your account.",
    "parent.inviteGenerated": "Share this code — it expires in 30 minutes and works once.",
    "parent.generateCode": "Generate invite code",
    "parent.inviteHeading": "Invite a parent",
    "parent.notAvailable": "Not available",
    "parent.back": "Back",
    "parent.noDataYet": "No data yet",
    "parent.notSyncedYet": "This student hasn't synced anything yet.",
    "parent.studentProgress": "Student progress",
    "parent.daysSessionsStat": "{days} day(s) studied · {sessions} session(s) completed",
    "parent.noMasteryData": "No mastery data yet.",
    "parent.questionsDue": "{n} question(s) due.",
    "parent.nothingDueNow": "Nothing due right now.",

    // ---- tutor chat ----
    "tutor.askPlaceholder": "Ask the tutor…",
    "tutor.voiceComingSoon": "Voice mode — coming soon",
    "tutor.voiceSoon": "soon",
    "tutor.voiceToast": "Voice mode is coming — you'll be able to talk through problems out loud.",
    "tutor.lockedDuringTest": "locked during the test",
    "tutor.yourTutor": "your tutor",
    "tutor.demoMode": "your tutor · demo mode",
    "tutor.sittingOut": "I'm sitting this one out.",
    "tutor.testExplain": "It's a test, so no hints — answer as best you can. When you finish I'll go through everything you missed with you.",
    "tutor.defaultCorrect": "That's right — well done!",
    "tutor.defaultEncourage": "Give it another try — you're close.",
    "tutor.snag": "The tutor hit a snag. Try again in a moment.",
    "tutor.celebrateDefault": "I got it right!",
    "tutor.opener0": "Have a look at this one — what's your first instinct?",
    "tutor.opener1": "Read it through once. What part of it do you already know something about?",
    "tutor.opener2": "Take a moment with this. What's the question really asking for?",
    "tutor.opener3": "What's the key word in this question? Start there.",
    "tutor.opener4": "Give it a go — I'll help if you get stuck.",

    // ---- settings (rest of the page) ----
    "settings.pageHeading": "Settings",
    "settings.appearance": "Appearance",
    "settings.theme": "Theme",
    "settings.accessibility": "Accessibility",
    "settings.dyslexiaMode": "Dyslexia-friendly mode",
    "settings.dyslexiaExplain": "Switches to Atkinson Hyperlegible — a typeface made for reading difficulties — with more line, letter and word spacing.",
    "settings.dyslexiaOn": "Dyslexia-friendly mode on",
    "settings.dyslexiaOff": "Dyslexia-friendly mode off",
    "settings.tutorServer": "Tutor server",
    "settings.tutorServerExplain": "Assignment generation and live tutoring are handled by a small backend that holds the Claude key — nothing to configure here. Without it reachable, StudyBuddy runs in demo mode on the sample content.",
    "settings.notReachable": "Not reachable — running in demo mode",
    "settings.connectedNoKey": "Connected, but no Claude key configured — running in demo mode",
    "settings.connectedLive": "Connected — live mode is on",
    "settings.modelTutor": "Model & tutor",
    "settings.modelTutorExplain": "StudyBuddy uses different Claude models for different jobs, so you're not paying top rates to mark a one-line answer.",
    "settings.qualityCost": "Quality & cost",
    "settings.tutorReplyLength": "Tutor reply length",
    "settings.writingSet": "Writing a set",
    "settings.tutoringYou": "Tutoring you",
    "settings.markingAnswers": "Marking answers",
    "settings.oncePerSet": "once per set",
    "settings.everyMessage": "every message",
    "settings.everyWrittenAnswer": "every written answer",
    "settings.concise": "Concise — short hints",
    "settings.normalDefault": "Normal (default)",
    "settings.detailed": "Detailed — fuller explanations",
    "settings.presetUpdated": "Model preset updated",
    "settings.tutorStyleUpdated": "Tutor style updated",
    "settings.themeUpdated": "Theme updated",
    "settings.yourData": "Your data",
    "settings.dataLocalSync": "Everything (assignments, attempts, progress) lives in this browser and syncs to your account.",
    "settings.dataLocalOnly": "Everything (assignments, attempts, progress) lives in this browser.",
    "settings.exportJson": "Export JSON",
    "settings.wipeAll": "Wipe all data",
    "settings.roadmap": "Roadmap",
    "settings.roadmapVoice": "Voice chat — talk through problems out loud",
    "settings.roadmapShare": "Share assignment sets with a friend",
    "settings.demoContent": "Demo content",
    "settings.demoIntro": "Two ready-made sets (Photosynthesis Basics, Ancient Rome Quiz) you can try without an API key — the tutor works in demo mode too.",
    "settings.demoPartial": "{loaded} of {total} demo sets are in your library. You can add the missing one back, or clear them out.",
    "settings.demoBothIn": "Both demo sets are in your library. They behave like any other set — study, edit, or delete them.",
    "settings.demoAddedOne": "Added 1 demo set",
    "settings.demoAddedMany": "Added {n} demo sets",
    "settings.demoAlreadyIn": "Already in your library",
    "settings.demoLoadFailed": "Couldn't load the demo sets",
    "settings.addMissingOne": "Add the missing one",
    "settings.loadDemoSets": "Load demo sets",
    "settings.removeDemoConfirm": "Remove the demo sets from your library?\n\nAny attempts you made on them stay in your history.",
    "settings.demoRemoved": "Demo sets removed",
    "settings.removeDemoSets": "Remove demo sets",
    "settings.account": "Account",
    "settings.signedInAs": "Signed in as {email}. Your library syncs to this account.",
    "settings.notSignedIn": "Not signed in — StudyBuddy works fully locally. Sign in to sync your library across devices.",
    "settings.parentLinking": "Parent / teacher linking",
    "settings.backupDownloaded": "Backup downloaded",
    "settings.deleteConfirm": "Delete all sets, attempts, and progress?\n\nThis can't be undone. Export a backup first if you want to keep it.",
    "settings.dataWiped": "Data wiped",

    // ---- claude client ----
    "claude.presetBalanced": "Balanced — recommended",
    "claude.presetBalancedHint": "Best model writes your questions; a lighter one marks answers. Good quality, much lower cost.",
    "claude.presetBest": "Best quality",
    "claude.presetBestHint": "Claude Opus 5 for everything. The strongest tutoring, and the most expensive.",
    "claude.presetCheapest": "Lowest cost",
    "claude.presetCheapestHint": "Fast and cheap throughout. Fine for drilling facts; weaker at explaining hard ideas.",
    "claude.networkError": "Network error — check your connection.",
    "claude.noKeyConfigured": "The tutor server isn't configured with a Claude key. Contact whoever's running this instance.",
    "claude.rateLimited": "Rate limited by the API — wait a moment and try again.",
    "claude.apiError": "API error {status}{detail}",
    "claude.untitledSet": "New assignment",
    "claude.tutorUnavailable": "Tutor unavailable (API {status}{detail}).",
    "claude.gradeNiceWork": "Nice work!",
    "claude.gradeNotQuite": "Not quite — take another look.",

    // ---- material extraction ----
    "material.pdfLoadFailed": "PDF reader failed to load. Refresh and try again.",
    "material.noSelectableText": "Couldn't find selectable text in that PDF. If it's a scan, upload it as a photo instead.",
    "material.zipLoadFailed": "ZIP reader failed to load. Refresh and try again.",
    "material.noPdfInZip": "Couldn't find a PDF in the ZIP file.",
    "material.noReadablePdf": "Couldn't read text from the PDFs in the ZIP file (they might be scanned pages).",
    "material.badImageType": "Please use a PNG, JPG, WEBP, or GIF image.",
    "material.imageTooBig": "That image is over 5 MB — try a smaller photo.",
    "material.couldNotRead": "Could not read that file.",
    "library.indexLoadFailed": "Couldn't load the practice library.",
    "library.setLoadFailed": "Couldn't load \"{title}\".",

    // ---- store fallbacks ----
    "store.untitled": "Untitled",
    "store.couldNotCreateAccount": "Could not create an account.",
    "store.couldNotSignIn": "Could not sign in.",
    "store.syncConflict": "Synced from another device — some local changes here were replaced.",
  },

  sv: {
    // ---- global chrome ----
    "nav.home": "Hem",
    "nav.library": "Bibliotek",
    "nav.create": "Skapa",
    "nav.progress": "Framsteg",
    "nav.parent": "Förälder/lärare",
    "nav.settings": "Inställningar",
    "nav.mainMenu": "Huvudmeny",

    "streak.days": "{n}-dagars streak",
    "streak.none": "Ingen streak än",

    "theme.group": "Tema",
    "theme.light": "Ljust",
    "theme.system": "Följ enheten",
    "theme.dark": "Mörkt",

    "topbar.notifications": "Notiser",
    "topbar.account": "Konto",
    "notif.dueReviewOne": "1 fråga väntar på repetition",
    "notif.dueReviewMany": "{n} frågor väntar på repetition",
    "notif.dueReviewBody": "Frågor från set du redan pluggat är redo att repeteras igen.",
    "notif.dueSinceToday": "Dags idag",
    "notif.dueSinceDayOne": "Väntat sedan 1 dag",
    "notif.dueSinceDayMany": "Väntat sedan {n} dagar",
    "notif.reviewNow": "Öva nu",
    "notif.examToday": "Provet är idag",
    "notif.examTomorrow": "Provet är imorgon",
    "notif.examInDays": "Provet är om {n} dagar",
    "notif.examBody": "Se till att dina repetitionsset är uppdaterade innan dess.",
    "notif.viewExam": "Visa",
    "notif.none": "Inga nya notiser.",
    "notif.noneRead": "Inget läst än.",
    "notif.panelTitle": "Notiser",
    "notif.tabUnread": "Olästa",
    "notif.tabRead": "Lästa",
    "notif.markRead": "Markera som läst",
    "account.signedInAs": "Inloggad som {email}",
    "account.settings": "Inställningar",
    "account.signOut": "Logga ut",
    "account.signOutDone": "Utloggad — lokalt läge",
    "account.signIn": "Logga in / skapa konto",

    "settings.language": "Språk",
    "settings.langUpdated": "Språk uppdaterat",
    "common.loading": "Laddar…",
    "common.error": "Något gick fel",
    "common.backToMenu": "Tillbaka till menyn",

    // ---- home page ----
    "greeting.morning": "God morgon",
    "greeting.afternoon": "God eftermiddag",
    "greeting.evening": "God kväll",
    "menu.hintLive": "Välj något att plugga på, eller skapa ett nytt set.",
    "menu.hintDemo": "Körs i demoläge — se Inställningar för hur du slår på live-läge.",
    "menu.newSet": "Nytt set",
    "menu.pageTitle": "Meny",

    "dash.noResults": "Inga resultat än",
    "dash.overallMastery": "Total nivå",
    "dash.startStudying": "Börja plugga",
    "dash.heroHintEmpty": "Slutför ett pass så dyker din nivå upp här.",
    "dash.heroHint": "{topics} spårade · {sessions} klara",
    "dash.topic": "1 område",
    "dash.topics": "{n} områden",
    "dash.session": "1 pass",
    "dash.sessions": "{n} pass",
    "dash.dayStreak": "dags streak",
    "dash.daysStreak": "dagars streak",
    "dash.streakEmpty": "Plugga idag för att starta en streak",
    "dash.dueNow": "Dags nu — tryck för att repetera",
    "dash.dueForReview": "Väntar på repetition",

    "today.continue": "Fortsätt där du slutade",
    "today.progress": "{title} · {n} av {total} besvarade",

    "sets.heading": "Dina set",
    "sets.searchPlaceholder": "Sök set…",
    "sets.sortNewest": "Nyast",
    "sets.sortAZ": "A–Ö",
    "sets.sortWeakest": "Svagast",
    "sets.tabAssignments": "Övningar",
    "sets.tabTests": "Prov",
    "sets.assignmentsNoun": "övningar",
    "sets.testsNoun": "prov",
    "sets.chipAll": "Alla",
    "sets.generalSubject": "Allmänt",
    "sets.newAssignment": "Ny övning",
    "sets.newTest": "Nytt prov",
    "sets.inProgress": "Pågående",
    "sets.answeredProgress": "{answered} av {total} besvarade",
    "sets.questionCount": "1 fråga",
    "sets.questionsCount": "{n} frågor",
    "sets.doneTimes": " · klar {n}×",
    "sets.setCount": "1 set",
    "sets.setsCount": "{n} set",
    "sets.noMatch": "Inga {tab} matchar ”{query}”. ",
    "sets.matchSwitch": "{n} {tab} matchar — byt till {target}",

    "empty.libraryTitle": "Ditt bibliotek är tomt",
    "empty.libraryBody": "Börja med färdiga övningar ur biblioteket — eller gör ett eget set från dina anteckningar, en PDF, ett foto eller bara ett ämne.",
    "empty.noAssignments": "Inga övningar än",
    "empty.noTests": "Inga prov än",
    "empty.assignmentBody": "Gör ett från dina anteckningar, en PDF, ett foto eller bara ett ämne.",
    "empty.testBody": "Skapa på samma sätt — markera det bara som ett prov.",
    "empty.openLibrary": "Öppna övningsbiblioteket",
    "empty.tryDemo": "Prova en demo",
    "empty.demoAdded": "Demo-set tillagda",
    "empty.demoFailed": "Kunde inte ladda demo-seten",

    "cardmenu.examMode": "Starta i provläge",
    "cardmenu.rename": "Byt namn",
    "cardmenu.editQuestions": "Redigera frågor",
    "cardmenu.duplicate": "Duplicera",
    "cardmenu.delete": "Ta bort",
    "cardmenu.renamePrompt": "Byt namn på detta set:",
    "cardmenu.renameNeedsName": "Ett set behöver ett namn",
    "cardmenu.renamed": "Namn ändrat",
    "cardmenu.copiedAs": "Kopierat som ”{title}”",
    "cardmenu.deleteConfirm": "Ta bort ”{title}”?{extra}\n\nDetta kan inte ångras.",
    "cardmenu.deleteExtra": "\n\nDetta tar även bort 1 registrerat försök från din historik.",
    "cardmenu.deleteExtraMany": "\n\nDetta tar även bort {n} registrerade försök från din historik.",
    "cardmenu.deleted": "Borttaget",

    "examcard.title": "Nästa prov",
    "examcard.date": "Datum",
    "examcard.about": "Vad handlar det om? (valfritt)",
    "examcard.aboutPlaceholder": "t.ex. Nationellt prov matematik",
    "examcard.save": "Spara",
    "examcard.cancel": "Avbryt",
    "examcard.change": "Ändra",
    "examcard.pickDateFirst": "Välj ett datum först",
    "examcard.past": "Har varit",
    "examcard.today": "Idag",
    "examcard.tomorrow": "Imorgon",
    "examcard.daysLeft": "{n} dagar kvar",

    "tips.heading": "Dagens studietips",
    "tips.0": "Testa dig själv innan du läser om ett kapitel — att aktivt minnas fastnar bättre än att bara läsa igen.",
    "tips.1": "Korta, återkommande pass slår långa plugg-maraton. Kör 25 fokuserade minuter, ta sedan en riktig paus.",
    "tips.2": "Blanda gärna flera ämnen istället för att köra ett i taget — hjärnan lär sig bättre av växling än av att nöta samma sak länge.",
    "tips.3": "Förklara det du just lärt dig högt för dig själv, som om du undervisade någon annan. Kan du inte förklara det enkelt kan du det inte riktigt än.",
    "tips.4": "Plugga det svåraste momentet först, medan du fortfarande är pigg och fokuserad.",
    "tips.5": "Sömn är en del av inlärningen — hjärnan befäster minnen medan du sover, så en sen kvällsrepetition är inte bortkastad.",
    "tips.6": "Gamla fel är guld värt. Gå igenom det du svarade fel på förra gången innan du kör ett nytt set.",

    // ---- study session ----
    "session.setGone": "Detta set finns inte längre.",
    "session.setEmpty": "Detta set har inga frågor än.",
    "session.questionsGone": "Dessa frågor är inte längre tillgängliga.",
    "session.resultGone": "Det resultatet är inte längre tillgängligt.",
    "session.noImportedSets": "Inga importerade set för det här ämnet ännu.",
    "session.notFoundTitle": "Hittades inte",
    "session.nothingToStudy": "Inget att plugga här",
    "session.reviewTitle": "Repetition",
    "session.reviewSessionTitle": "Repetitionspass",
    "session.nothingDue": "Inget att repetera just nu",
    "session.nothingDueBody": "Spaced repetition tar fram frågor strax innan du skulle glömma dem. Kom tillbaka imorgon, eller plugga ett set för att lägga till fler.",
    "session.practiceTitle": "Träning",
    "session.nothingToPractice": "Inget att träna på",
    "session.nothingToPracticeBody": "Du hade rätt på allt i det passet.",
    "session.mixedTitle": "Blandat – {subject}",
    "session.nationalTest": "Nationellt prov",
    "session.next": "Nästa",
    "session.finish": "Klar",
    "session.skip": "Hoppa över",
    "session.exit": "Avsluta",
    "session.timeUp": "Tiden är ute — dina svar skickades in automatiskt.",
    "session.skippedAnnounce": "Överhoppad. Du ser den igen på slutet.",
    "session.questionAnnounce": "Fråga {n} av {total}.",
    "session.progressLabel": "Fråga {n} av {total} · {done} besvarade",
    "session.progressSkipped": " · {n} överhoppade",
    "session.exitConfirm": "Lämna det här passet?\n\nDina framsteg är sparade — du kan fortsätta där du slutade.",
    "session.resumeTitle": "Fortsätta där du slutade?",
    "session.resumeBodyOne": "Du svarade på {done} av {total} fråga förra gången",
    "session.resumeBodyMany": "Du svarade på {done} av {total} frågor förra gången",
    "session.resumeMore": " — {n} kvar.",
    "session.resumeReady": ", så du är redo att avsluta.",
    "session.continue": "Fortsätt",
    "session.startOver": "Börja om",
    "session.shortcutsTitle": "Kortkommandon",
    "session.shortcutPickMc": "Välj ett flervalssvar",
    "session.shortcutCheck": "Kontrollera ditt svar, gå sedan vidare",
    "session.shortcutNext": "Nästa fråga",
    "session.shortcutSkip": "Hoppa över",
    "session.shortcutFlip": "Vänd på ett flashcard",
    "session.shortcutShow": "Visa den här listan",
    "session.close": "Stäng",
    "session.needHint": "Behöver du en ledtråd?",
    "session.hideTutor": "Dölj handledaren",
    "session.testModeWarn": "Provläge: ett försök per fråga och inga ledtrådar. Handledaren går igenom det med dig efteråt.",
    "session.kbdHintPre": "Tips: tryck på ",
    "session.kbdHintPost": " för kortkommandon.",
    "session.badgeReview": "Repetition",
    "session.badgePractice": "Träning",
    "session.badgeExamMode": "Provläge",
    "session.badgeAssignment": "Övning",
    "session.badgeTest": "Prov",

    // ---- question renderers ----
    "q.listenQuestion": "Läs upp frågan",
    "q.listen": "Läs upp",
    "q.checkAnswer": "Kontrollera svar",
    "q.answerRecorded": "Svar registrerat.",
    "q.correctBang": "Rätt!",
    "q.retryHint": "Fortfarande inte rätt. Läs handledarens ledtråd och försök igen — eller visa svaret nedan.",
    "q.tryAgain": "Inte riktigt — försök igen.",
    "q.revealAnswer": "Visa svar & fortsätt",
    "q.answerIs": "Svaret är {letter}.",
    "q.wrongChoiceNote": "Jag valde \"{choice}\" och det var fel. Kan du hjälpa mig förstå varför?",
    "q.celebrateChoice": "Jag valde rätt!",
    "q.yourAnswerPlaceholder": "Skriv ditt svar…",
    "q.submitAnswer": "Skicka in svar",
    "q.submitting": "Skickar…",
    "q.checking": "Kontrollerar…",
    "q.modelAnswerLabel": "Modellsvar:",
    "q.celebrateText": "Jag tror jag hade rätt på den.",
    "q.wroteNote": "Så här skrev jag: \"{answer}\". Vad saknas?",
    "q.markedCorrect": "Markerad som rätt. Kolla ändå på modellsvaret — lätt att missa en detalj.",
    "q.disagree": "Håller du inte med om bedömningen? ",
    "q.iThinkRight": "Jag tycker mitt svar var rätt",
    "q.rateAgain": "Igen",
    "q.rateHard": "Svårt",
    "q.rateGood": "Bra",
    "q.rateEasy": "Lätt",
    "q.forgotNote": "Jag kunde inte komma ihåg den här. Kan du hjälpa mig så den fastnar?",
    "q.rememberedCelebrate": "Kom ihåg den!",
    "q.tapToFlip": "Tryck på kortet för att vända, eller tryck mellanslag.",
    "q.workHerePlain": "Räkna här.",
    "q.workHereTutor": "Räkna här — handledaren till höger hjälper dig.",
    "q.showStep": "Visa ett steg",
    "q.doneShowAnswer": "Jag är klar — visa svaret",
    "q.revealStepNote": "Jag har visat steg {n}. Kan du peta mig mot nästa del?",
    "q.leftBlank": "Lämnades tomt.",
    "q.fullSolutionLabel": "Fullständig lösning:",
    "q.reasoningCheck": "Kom ditt resonemang fram till svaret?",
    "q.hadIt": "Ja, jag hade rätt",
    "q.notQuite": "Inte riktigt",
    "q.heuristicNoModel": "Jämför ditt svar med modellsvaret nedan.",
    "q.heuristicGood": "Det täcker huvudpoängerna — kolla detaljerna nedan.",
    "q.heuristicMissing": "Det verkar saknas några av huvudpoängerna. Jämför med modellsvaret nedan.",

    // ---- results screen ----
    "results.noResults": "Inga resultat att visa",
    "results.genericSession": "Session",
    "results.great": "Snyggt jobbat",
    "results.niceEffort": "Bra ansträngning",
    "results.examModeSuffix": " · provläge",
    "results.testSuffix": " · prov",
    "results.limitSuffix": " (gräns {n} min)",
    "results.timedOut": "Tiden tog slut — detta skickades in automatiskt.",
    "results.topicMastery": "Nivå per ämnesområde",
    "results.worthAnotherLook": "Värt en till titt",
    "results.practiseOne": "Träna på den nu",
    "results.practiseMany": "Träna på dessa {n} nu",
    "results.tutorSatOut": "Handledaren höll sig undan under provet — nu går den igenom dessa med dig.",
    "results.reviewAgain": "Repetera igen",
    "results.tryAgain": "Försök igen",
    "results.seeProgress": "Se framsteg",
    "results.pageTitle": "Resultat",
    "results.correctCount": "{c} / {n} rätt",
    "results.tookHours": "Tog {h}h {m}m",
    "results.tookSecs": "Tog {n}s",
    "results.tookMin": "Tog {n} min",
    "results.tookMin30": "Tog {n} min 30s",
    "results.gradeEyebrow": "Uppskattat betyg",
    "results.gradeFirstTime": "Ditt första resultat på det här — bra riktmärke att slå nästa gång.",
    "results.gradeUpFrom": "Upp från {letter} — ditt bästa på det här hittills.",
    "results.gradeMatchesBest": "Samma som ditt bästa på det här hittills.",
    "results.gradeBestSoFar": "Ditt bästa på det här är fortfarande {letter} — värt ett försök till.",

    // ---- spaced repetition due labels ----
    "srs.dueNow": "nu",
    "srs.tomorrow": "imorgon",
    "srs.inDays": "om {n} dagar",
    "srs.inWeeks": "om {n} v",
    "srs.inMonths": "om {n} mån",

    // ---- progress page ----
    "progress.title": "Dina framsteg",
    "progress.pageTitle": "Framsteg",
    "progress.studyStreak": "Studiestreak",
    "progress.studiedDays": "1 dag pluggad",
    "progress.studiedDaysMany": "{n} dagar pluggade",
    "progress.sessionsOne": "1 pass klart",
    "progress.sessionsMany": "{n} pass klara",
    "progress.masteryBySubject": "Nivå per ämne",
    "progress.gradeExplain": "Bokstaven är en uppskattad nivå (E–A) baserat på hur du presterat i dina övningar — inte ett riktigt betyg.",
    "progress.gradeTooltip": "Uppskattad nivå {letter} baserat på dina svar — inte ett riktigt betyg",
    "progress.noMasteryYet": "Slutför ett pass för att börja bygga upp din nivå. Svagaste ämnesområdena visas först.",
    "progress.dueForReview": "Väntar på repetition",
    "progress.reviewToday": "Repetera idag",
    "progress.reviewTodayExplain": "”Repetera idag” tränar bara på dessa frågor, hämtade från alla dina set.",
    "progress.moreItems": "+ {n} till",
    "progress.nothingDue": "Inget att repetera just nu. Spaced repetition tar fram frågor strax innan du skulle glömma dem.",

    // ---- create flow ----
    "create.title": "Nytt övningsset",
    "create.pageTitle": "Nytt set",
    "create.stepSource": "Källa",
    "create.stepMaterial": "Material",
    "create.stepReview": "Granska",
    "create.sourceQuestion": "Var ska frågorna komma ifrån?",
    "create.sourcePaste": "Klistra in text",
    "create.sourcePasteDesc": "Anteckningar, en artikel, ett kapitel",
    "create.sourcePdf": "Ladda upp PDF",
    "create.sourcePdfDesc": "Ett arbetsblad, en lärobokssida, eller ZIP",
    "create.sourcePhoto": "Ladda upp foto",
    "create.sourcePhotoDesc": "En bild på en sida eller tavla",
    "create.sourceTopic": "Bara ett ämne",
    "create.sourceTopicDesc": "t.ex. ”Bråk i årskurs 5”",
    "create.sourceNational": "Nationellt prov",
    "create.sourceNationalDesc": "Öva inför nationella prov",
    "create.needsServerPre": "Generering kräver handledarservern (se ",
    "create.needsServerPost": ") — eller utforska exempelsetet i menyn tills vidare.",
    "create.reading": "Läser…",
    "create.zipExtracted": "Extraherade text från {pdfCount} av {totalPdfCount} {noun} i \"{name}\"{audioNote}.",
    "create.pdfFile": "PDF-fil",
    "create.pdfFiles": "PDF-filer",
    "create.audioSkippedOne": " ({n} ljudfil ignorerades)",
    "create.audioSkippedMany": " ({n} ljudfiler ignorerades)",
    "create.pdfExtracted": "Extraherade {n} tecken från \"{name}\".",
    "create.readError": "Kunde inte läsa den filen.",
    "create.pdfOrZipLabel": "PDF- eller ZIP-fil",
    "create.importedSetsOne": "1 importerat set för det här ämnet:",
    "create.importedSetsMany": "{n} importerade set för det här ämnet:",
    "create.setQuestionsOne": "→ {title} (1 fråga)",
    "create.setQuestionsMany": "→ {title} ({n} frågor)",
    "create.mixAllYears": "Blanda alla år — antal frågor:",
    "create.startMix": "Starta blandning",
    "create.exampleBadge": "Exempel",
    "create.externalBadge": "Extern sida",
    "create.getMaterial": "Hämta provmaterial ↗",
    "create.limitedExplain": "Riktiga gamla prov i det här ämnet innehåller upphovsrättsskyddade texter, så bara exempeluppgifter är fritt publicerade — länken visar dem. Fullständiga gamla prov måste begäras ut från Skolverket som en \"begäran om allmän handling\".",
    "create.externalExplain": "Öppnar en sida med gamla prov hos ett universitet — hämta det du vill öva på (PDF, ZIP eller vad de erbjuder), ladda sedan upp eller klistra in det här.",
    "create.levelPlaceholder": "Välj nivå…",
    "create.levelLabel": "Nivå",
    "create.subjectPlaceholder": "Välj ämne…",
    "create.subjectLabel": "Ämne",
    "create.typeLabel": "Typ",
    "create.pasteExcerptPlaceholder": "Klistra in ett utdrag ur provet här (valfritt om du laddar upp filen nedan)…",
    "create.pasteTextLabel": "Klistra in text",
    "create.pastePlaceholder": "Klistra in dina anteckningar eller läsning här…",
    "create.studyMaterialLabel": "Studiematerial",
    "create.topicPlaceholder": "t.ex. Vattnets kretslopp, årskurs 4",
    "create.topicLabel": "Ämne",
    "create.yearAgePlaceholder": "t.ex. Årskurs 8 / 13 år (valfritt)",
    "create.yearAgeLabel": "Årskurs / åldersnivå",
    "create.photoLabel": "Foto",
    "create.loaded": "Läste in \"{name}\".",
    "create.assignmentOption": "Övning (träning)",
    "create.testOption": "Prov (quiz)",
    "create.howManyQuestions": "Hur många frågor",
    "create.preferFlashcards": "Föredra flashcards",
    "create.generate": "Generera frågor",
    "create.addMaterialFirst": "Lägg till material eller ett ämne först.",
    "create.generationFailed": "Genereringen misslyckades. Försök igen eller förenkla materialet.",
    "create.back": "Tillbaka",
    "create.writingQuestions": "Skriver dina frågor…",
    "create.usuallyTakes": "Detta tar oftast 10–30 sekunder.",
    "create.setTitleLabel": "Titel",
    "create.questionCountOne": "1 fråga · redigera vad som helst nedan, spara sedan.",
    "create.questionCountMany": "{n} frågor · redigera vad som helst nedan, spara sedan.",
    "create.addQuestion": "+ fråga",
    "create.saveSet": "Spara set",
    "create.needQuestion": "Lägg till minst en fråga.",
    "create.needName": "Ge setet ett namn.",
    "create.saved": "Sparat!",
    "create.subjectLocked": "Låst till nationellt prov-ämne",

    // ---- edit set ----
    "edit.title": "Redigera set",
    "edit.pageTitle": "Redigera — {title}",
    "edit.setName": "Ge setet ett namn",
    "edit.needQuestion": "Ett set behöver minst en fråga",
    "edit.saved": "Sparat",
    "edit.cancel": "Avbryt",
    "edit.saveChanges": "Spara ändringar",
    "edit.questionCountOne": "1 fråga",
    "edit.questionCountMany": "{n} frågor",

    // ---- question editor ----
    "qedit.mc": "Flervalsfråga",
    "qedit.text": "Kort svar",
    "qedit.flashcard": "Flashcard",
    "qedit.worked": "Räkneuppgift",
    "qedit.noQuestions": "Inga frågor än — lägg till en nedan.",
    "qedit.selectCorrect": "Markera radioknappen bredvid det rätta alternativet.",
    "qedit.addChoice": "+ alternativ",
    "qedit.backOfCard": "Kortets baksida",
    "qedit.modelAnswer": "Modellsvar",
    "qedit.topicPlaceholder": "ämnesområde",
    "qedit.deleteQuestion": "Ta bort fråga",
    "qedit.questionLabel": "Fråga",

    // ---- övningsbibliotek ----
    "library.pageTitle": "Övningsbibliotek",
    "library.loadFailed": "Kunde inte ladda biblioteket",
    "library.tryAgain": "Försök igen om en stund.",
    "library.toHome": "Till startsidan",
    "library.searchPlaceholder": "Sök i biblioteket — ämne, kurs eller set…",
    "library.searchAria": "Sök i övningsbiblioteket",
    "library.back": "Tillbaka",
    "library.noMatches": "Inga träffar för \"{query}\". Prova ett ämne, en kurs eller en årskurs.",
    "library.matchOne": "1 träff",
    "library.matchMany": "{n} träffar",
    "library.levelIntro": "Färdiga övningar du kan börja plugga på direkt — ingen egen uppladdning behövs. Välj nivå för att se ämnen.",
    "library.subjectIntro": "{level} — vilket ämne vill du plugga?",
    "library.addAll": "Lägg till alla ({n})",
    "library.addedOne": "La till 1 set",
    "library.addedMany": "La till {n} set",
    "library.allAlready": "Allt fanns redan i ditt bibliotek",
    "library.allAdded": "Alla set tillagda ✓",
    "library.study": "Plugga",
    "library.add": "Lägg till",
    "library.added": "”{title}” tillagt",
    "library.addFailed": "Kunde inte lägga till setet",
    "library.examMode": "Provläge",
    "library.examModeTooltip": "Provläge: tidtagning, inga ledtrådar och facit visas först när du är klar.",
    "library.questionsOne": "1 fråga",
    "library.questionsMany": "{n} frågor",
    "library.levelAk7": "Årskurs 7",
    "library.levelAk8": "Årskurs 8",
    "library.levelAk9": "Årskurs 9",
    "library.levelGymnasiet": "Gymnasiet",

    // ---- logga in ----
    "login.signIn": "Logga in",
    "login.createAccount": "Skapa konto",
    "login.needAccount": "Inget konto? Skapa ett",
    "login.haveAccount": "Har du redan ett konto? Logga in",
    "login.atLeast8": "Minst 8 tecken",
    "login.signedIn": "Inloggad — synk är på",
    "login.accountCreated": "Konto skapat — synk är på",
    "login.somethingWrong": "Något gick fel.",
    "login.email": "E-post",
    "login.password": "Lösenord",
    "login.pageHeading": "Konto",
    "login.intro": "Logga in för att synka ditt bibliotek och dina framsteg mellan enheter. Helt valfritt — StudyBuddy funkar lokalt även om du hoppar över det här.",
    "login.backendDown": "Backend-servern går inte att nå just nu — inloggning funkar inte förrän den gör det.",
    "login.backToSettings": "Tillbaka till inställningar",
    "login.pageTitle": "Logga in",

    // ---- förälder / lärare ----
    "parent.title": "Förälder/lärare",
    "parent.requestFailed": "Begäran misslyckades.",
    "parent.signInIntro": "Logga in för att länka konton, tilldela uppgifter och se framsteg.",
    "parent.studentsHeading": "Elever du är länkad till",
    "parent.noneYet": "Inga än — lös in en elevs inbjudningskod nedan.",
    "parent.unlinkConfirm": "Ta bort länken till {email}?",
    "parent.unlink": "Ta bort länk",
    "parent.assignSet": "Tilldela ett set",
    "parent.noOwnSets": "Du har inga egna set att tilldela än — skapa ett från menyn först.",
    "parent.assign": "Tilldela",
    "parent.assignedToast": "Tilldelade ”{title}” till {email}",
    "parent.inviteCodePlaceholder": "t.ex. AB12CD",
    "parent.link": "Länka",
    "parent.linkedTo": "Länkad till {email}",
    "parent.haveCode": "Har du en elevs inbjudningskod?",
    "parent.parentsHeading": "Föräldrar/lärare länkade till dig",
    "parent.noParentsYet": "Ingen än. Skapa en kod ovan och dela den med en förälder eller lärare.",
    "parent.assignedHeading": "Tilldelat till dig",
    "parent.couldntLoadAssigned": "Kunde inte ladda tilldelade set.",
    "parent.nothingWaiting": "Inget väntar just nu.",
    "parent.addToLibrary": "Lägg till i mitt bibliotek",
    "parent.addedToLibrary": "La till ”{title}” i ditt bibliotek",
    "parent.fromEmail": "från {email}",
    "parent.inviteStatus": "Skapa en kod och dela den med en förälder eller lärare så kan de länka till ditt konto.",
    "parent.inviteGenerated": "Dela den här koden — den gäller i 30 minuter och funkar en gång.",
    "parent.generateCode": "Skapa inbjudningskod",
    "parent.inviteHeading": "Bjud in en förälder",
    "parent.notAvailable": "Inte tillgängligt",
    "parent.back": "Tillbaka",
    "parent.noDataYet": "Ingen data än",
    "parent.notSyncedYet": "Den här eleven har inte synkat något än.",
    "parent.studentProgress": "Elevens framsteg",
    "parent.daysSessionsStat": "{days} dag(ar) pluggade · {sessions} pass klara",
    "parent.noMasteryData": "Ingen nivådata än.",
    "parent.questionsDue": "{n} fråg(or) väntar.",
    "parent.nothingDueNow": "Inget att repetera just nu.",

    // ---- handledarchatt ----
    "tutor.askPlaceholder": "Fråga handledaren…",
    "tutor.voiceComingSoon": "Röstläge — kommer snart",
    "tutor.voiceSoon": "snart",
    "tutor.voiceToast": "Röstläge är på väg — du kommer kunna prata igenom problem högt.",
    "tutor.lockedDuringTest": "låst under provet",
    "tutor.yourTutor": "din handledare",
    "tutor.demoMode": "din handledare · demoläge",
    "tutor.sittingOut": "Jag håller mig undan den här gången.",
    "tutor.testExplain": "Det är ett prov, så inga ledtrådar — svara så gott du kan. När du är klar går jag igenom allt du missade med dig.",
    "tutor.defaultCorrect": "Det stämmer — bra jobbat!",
    "tutor.defaultEncourage": "Försök igen — du är nära.",
    "tutor.snag": "Handledaren stötte på ett problem. Försök igen om en stund.",
    "tutor.celebrateDefault": "Jag fick rätt!",
    "tutor.opener0": "Titta på den här — vad är din första instinkt?",
    "tutor.opener1": "Läs igenom den en gång. Vilken del känner du redan till något om?",
    "tutor.opener2": "Ta en stund med den här. Vad frågar frågan egentligen efter?",
    "tutor.opener3": "Vad är nyckelordet i frågan? Börja där.",
    "tutor.opener4": "Testa — jag hjälper till om du fastnar.",

    // ---- inställningar (resten av sidan) ----
    "settings.pageHeading": "Inställningar",
    "settings.appearance": "Utseende",
    "settings.theme": "Tema",
    "settings.accessibility": "Tillgänglighet",
    "settings.dyslexiaMode": "Dyslexivänligt läge",
    "settings.dyslexiaExplain": "Byter till Atkinson Hyperlegible — ett typsnitt gjort för lässvårigheter — med större rad-, bokstavs- och ordavstånd.",
    "settings.dyslexiaOn": "Dyslexivänligt läge på",
    "settings.dyslexiaOff": "Dyslexivänligt läge av",
    "settings.tutorServer": "Handledarserver",
    "settings.tutorServerExplain": "Genereringen av övningar och den direkta handledningen sköts av en liten backend som håller i Claude-nyckeln — inget att ställa in här. Utan kontakt med den körs StudyBuddy i demoläge med exempelinnehåll.",
    "settings.notReachable": "Går inte att nå — körs i demoläge",
    "settings.connectedNoKey": "Ansluten, men ingen Claude-nyckel konfigurerad — körs i demoläge",
    "settings.connectedLive": "Ansluten — live-läge är på",
    "settings.modelTutor": "Modell & handledare",
    "settings.modelTutorExplain": "StudyBuddy använder olika Claude-modeller för olika uppgifter, så du betalar inte toppris för att rätta ett enradigt svar.",
    "settings.qualityCost": "Kvalitet & kostnad",
    "settings.tutorReplyLength": "Handledarens svarslängd",
    "settings.writingSet": "Skriver ett set",
    "settings.tutoringYou": "Handleder dig",
    "settings.markingAnswers": "Rättar svar",
    "settings.oncePerSet": "en gång per set",
    "settings.everyMessage": "varje meddelande",
    "settings.everyWrittenAnswer": "varje skrivet svar",
    "settings.concise": "Kortfattat — korta ledtrådar",
    "settings.normalDefault": "Normal (standard)",
    "settings.detailed": "Utförligt — fylligare förklaringar",
    "settings.presetUpdated": "Modellinställning uppdaterad",
    "settings.tutorStyleUpdated": "Handledarstil uppdaterad",
    "settings.themeUpdated": "Tema uppdaterat",
    "settings.yourData": "Din data",
    "settings.dataLocalSync": "Allt (övningar, försök, framsteg) lagras i den här webbläsaren och synkas till ditt konto.",
    "settings.dataLocalOnly": "Allt (övningar, försök, framsteg) lagras i den här webbläsaren.",
    "settings.exportJson": "Exportera JSON",
    "settings.wipeAll": "Radera all data",
    "settings.roadmap": "På gång",
    "settings.roadmapVoice": "Röstchatt — prata igenom problem högt",
    "settings.roadmapShare": "Dela övningsset med en kompis",
    "settings.demoContent": "Demo-innehåll",
    "settings.demoIntro": "Två färdiga set (Fotosyntes grunder, Antikens Rom-quiz) du kan testa utan API-nyckel — handledaren funkar i demoläge också.",
    "settings.demoPartial": "{loaded} av {total} demo-set finns i ditt bibliotek. Du kan lägga tillbaka det som saknas, eller rensa bort dem.",
    "settings.demoBothIn": "Båda demo-seten finns i ditt bibliotek. De fungerar som vilket set som helst — plugga, redigera eller ta bort dem.",
    "settings.demoAddedOne": "La till 1 demo-set",
    "settings.demoAddedMany": "La till {n} demo-set",
    "settings.demoAlreadyIn": "Fanns redan i ditt bibliotek",
    "settings.demoLoadFailed": "Kunde inte ladda demo-seten",
    "settings.addMissingOne": "Lägg till det som saknas",
    "settings.loadDemoSets": "Ladda demo-set",
    "settings.removeDemoConfirm": "Ta bort demo-seten från ditt bibliotek?\n\nEventuella försök du gjort på dem finns kvar i din historik.",
    "settings.demoRemoved": "Demo-set borttagna",
    "settings.removeDemoSets": "Ta bort demo-set",
    "settings.account": "Konto",
    "settings.signedInAs": "Inloggad som {email}. Ditt bibliotek synkas till det här kontot.",
    "settings.notSignedIn": "Inte inloggad — StudyBuddy funkar helt lokalt. Logga in för att synka ditt bibliotek mellan enheter.",
    "settings.parentLinking": "Förälder/lärare-länkning",
    "settings.backupDownloaded": "Säkerhetskopia nedladdad",
    "settings.deleteConfirm": "Ta bort alla set, försök och framsteg?\n\nDetta kan inte ångras. Exportera en säkerhetskopia först om du vill spara den.",
    "settings.dataWiped": "Data raderad",

    // ---- claude-klienten ----
    "claude.presetBalanced": "Balanserad — rekommenderas",
    "claude.presetBalancedHint": "Bästa modellen skriver dina frågor; en lättare rättar svar. Bra kvalitet, mycket lägre kostnad.",
    "claude.presetBest": "Bäst kvalitet",
    "claude.presetBestHint": "Claude Opus 5 för allt. Starkast handledning, och dyrast.",
    "claude.presetCheapest": "Lägst kostnad",
    "claude.presetCheapestHint": "Snabbt och billigt rakt igenom. Bra för att träna fakta; svagare på att förklara svåra idéer.",
    "claude.networkError": "Nätverksfel — kontrollera din anslutning.",
    "claude.noKeyConfigured": "Handledarservern har ingen Claude-nyckel konfigurerad. Kontakta den som driftar den här instansen.",
    "claude.rateLimited": "Begränsad av API:et — vänta en stund och försök igen.",
    "claude.apiError": "API-fel {status}{detail}",
    "claude.untitledSet": "Namnlöst set",
    "claude.tutorUnavailable": "Handledaren är inte tillgänglig (API {status}{detail}).",
    "claude.gradeNiceWork": "Bra jobbat!",
    "claude.gradeNotQuite": "Inte riktigt — titta en gång till.",

    // ---- materialutvinning ----
    "material.pdfLoadFailed": "PDF-läsaren kunde inte laddas. Uppdatera sidan och försök igen.",
    "material.noSelectableText": "Kunde inte hitta markerbar text i den PDF:en. Om det är en skanning, ladda upp den som ett foto istället.",
    "material.zipLoadFailed": "ZIP-läsaren kunde inte laddas. Uppdatera sidan och försök igen.",
    "material.noPdfInZip": "Hittade ingen PDF i zip-filen.",
    "material.noReadablePdf": "Kunde inte läsa text ur PDF-filerna i zip-filen (kan vara skannade sidor).",
    "material.badImageType": "Använd en PNG-, JPG-, WEBP- eller GIF-bild.",
    "material.imageTooBig": "Bilden är över 5 MB — prova ett mindre foto.",
    "material.couldNotRead": "Kunde inte läsa den filen.",
    "library.indexLoadFailed": "Kunde inte ladda övningsbiblioteket.",
    "library.setLoadFailed": "Kunde inte ladda ”{title}”.",

    // ---- store-standardvärden ----
    "store.untitled": "Namnlöst",
    "store.couldNotCreateAccount": "Kunde inte skapa ett konto.",
    "store.couldNotSignIn": "Kunde inte logga in.",
    "store.syncConflict": "Synkat från en annan enhet — vissa lokala ändringar här ersattes.",
  },
};
