// Translation strings: English (fallback) + Swedish.
//
// Covers the global chrome (sidebar, topbar, popovers) and the home page —
// see js/lib/i18n.js for how these are looked up. Other views still have
// their user-facing text hardcoded in English/Swedish directly; this file
// grows as more views get wired up to t().

export const STRINGS = {
  en: {
    // ---- global chrome ----
    "nav.home": "Home",
    "nav.library": "Library",
    "nav.create": "Create",
    "nav.progress": "Progress",
    "nav.parent": "Parent / teacher",
    "nav.settings": "Settings",
    "nav.mainMenu": "Main menu",

    "streak.days": "{n}-day streak",
    "streak.none": "No streak yet",

    "theme.group": "Theme",
    "theme.light": "Light",
    "theme.system": "Match my device",
    "theme.dark": "Dark",

    "topbar.notifications": "Notifications",
    "topbar.account": "Account",
    "notif.dueReviewOne": "1 question waiting for review",
    "notif.dueReviewMany": "{n} questions waiting for review",
    "notif.examToday": "The exam is today",
    "notif.examTomorrow": "The exam is tomorrow",
    "notif.examInDays": "The exam is in {n} days",
    "notif.none": "No new notifications.",
    "account.signedInAs": "Signed in as {email}",
    "account.settings": "Settings",
    "account.signOut": "Sign out",
    "account.signOutDone": "Signed out — local mode",
    "account.signIn": "Sign in / create account",

    "settings.language": "Language",
    "settings.langUpdated": "Language updated",
    "common.loading": "Loading…",
    "common.error": "Something went wrong",
    "common.backToMenu": "Back to menu",

    // ---- home page ----
    "greeting.morning": "Good morning",
    "greeting.afternoon": "Good afternoon",
    "greeting.evening": "Good evening",
    "menu.hintLive": "Pick something to study, or make a new set.",
    "menu.hintDemo": "Running in demo mode — see Settings for how to turn on live mode.",
    "menu.newSet": "New set",
    "menu.pageTitle": "Menu",

    "dash.noResults": "No results yet",
    "dash.overallMastery": "Overall mastery",
    "dash.startStudying": "Start studying",
    "dash.heroHintEmpty": "Finish a session and your level shows up here.",
    "dash.heroHint": "{topics} tracked · {sessions} done",
    "dash.topic": "1 topic",
    "dash.topics": "{n} topics",
    "dash.session": "1 session",
    "dash.sessions": "{n} sessions",
    "dash.dayStreak": "day streak",
    "dash.daysStreak": "days streak",
    "dash.streakEmpty": "Study today to start a streak",
    "dash.dueNow": "Due now — tap to review",
    "dash.dueForReview": "Due for review",

    "today.continue": "Continue where you left off",
    "today.progress": "{title} · {n} of {total} answered",

    "sets.heading": "Your sets",
    "sets.searchPlaceholder": "Search sets…",
    "sets.sortNewest": "Newest",
    "sets.sortAZ": "A–Z",
    "sets.sortWeakest": "Weakest",
    "sets.tabAssignments": "Assignments",
    "sets.tabTests": "Tests",
    "sets.assignmentsNoun": "assignments",
    "sets.testsNoun": "tests",
    "sets.chipAll": "All",
    "sets.generalSubject": "General",
    "sets.newAssignment": "New assignment",
    "sets.newTest": "New test",
    "sets.inProgress": "In progress",
    "sets.answeredProgress": "{answered} of {total} answered",
    "sets.questionCount": "1 question",
    "sets.questionsCount": "{n} questions",
    "sets.doneTimes": " · done {n}×",
    "sets.setCount": "1 set",
    "sets.setsCount": "{n} sets",
    "sets.noMatch": "No {tab} match “{query}”. ",
    "sets.matchSwitch": "{n} {tab} match — switch to {target}",

    "empty.libraryTitle": "Your library is empty",
    "empty.libraryBody": "Start with ready-made sets from the library — or make your own from your notes, a PDF, a photo, or just a topic.",
    "empty.noAssignments": "No assignments yet",
    "empty.noTests": "No tests yet",
    "empty.assignmentBody": "Make one from your notes, a PDF, a photo, or just a topic.",
    "empty.testBody": "Create one the same way — just mark it as a test.",
    "empty.openLibrary": "Open the practice library",
    "empty.tryDemo": "Try a demo",
    "empty.demoAdded": "Demo sets added",
    "empty.demoFailed": "Couldn't load the demo sets",

    "cardmenu.examMode": "Start in exam mode",
    "cardmenu.rename": "Rename",
    "cardmenu.editQuestions": "Edit questions",
    "cardmenu.duplicate": "Duplicate",
    "cardmenu.delete": "Delete",
    "cardmenu.renamePrompt": "Rename this set:",
    "cardmenu.renameNeedsName": "A set needs a name",
    "cardmenu.renamed": "Renamed",
    "cardmenu.copiedAs": "Copied as “{title}”",
    "cardmenu.deleteConfirm": "Delete “{title}”?{extra}\n\nThis can't be undone.",
    "cardmenu.deleteExtra": "\n\nThis also removes 1 recorded attempt from your history.",
    "cardmenu.deleteExtraMany": "\n\nThis also removes {n} recorded attempts from your history.",
    "cardmenu.deleted": "Deleted",

    "examcard.title": "Next exam",
    "examcard.date": "Date",
    "examcard.about": "What's it about? (optional)",
    "examcard.aboutPlaceholder": "e.g. National test in maths",
    "examcard.save": "Save",
    "examcard.cancel": "Cancel",
    "examcard.change": "Change",
    "examcard.pickDateFirst": "Pick a date first",
    "examcard.past": "Already happened",
    "examcard.today": "Today",
    "examcard.tomorrow": "Tomorrow",
    "examcard.daysLeft": "{n} days left",

    "tips.heading": "Today's study tip",
    "tips.0": "Test yourself before re-reading a chapter — actively recalling sticks better than just reading it again.",
    "tips.1": "Short, repeated sessions beat long cram marathons. Do 25 focused minutes, then take a real break.",
    "tips.2": "Mix several subjects instead of grinding one at a time — your brain learns better from switching than from repeating the same thing for hours.",
    "tips.3": "Explain what you just learned out loud, as if teaching someone else. If you can't explain it simply, you don't quite have it yet.",
    "tips.4": "Study the hardest part first, while you're still fresh and focused.",
    "tips.5": "Sleep is part of learning — your brain consolidates memories while you sleep, so a late review session isn't wasted.",
    "tips.6": "Old mistakes are worth gold. Go over what you got wrong last time before starting a new set.",
  },

  sv: {
    // ---- global chrome ----
    "nav.home": "Hem",
    "nav.library": "Bibliotek",
    "nav.create": "Skapa",
    "nav.progress": "Framsteg",
    "nav.parent": "Förälder/lärare",
    "nav.settings": "Inställningar",
    "nav.mainMenu": "Huvudmeny",

    "streak.days": "{n}-dagars streak",
    "streak.none": "Ingen streak än",

    "theme.group": "Tema",
    "theme.light": "Ljust",
    "theme.system": "Följ enheten",
    "theme.dark": "Mörkt",

    "topbar.notifications": "Notiser",
    "topbar.account": "Konto",
    "notif.dueReviewOne": "1 fråga väntar på repetition",
    "notif.dueReviewMany": "{n} frågor väntar på repetition",
    "notif.examToday": "Provet är idag",
    "notif.examTomorrow": "Provet är imorgon",
    "notif.examInDays": "Provet är om {n} dagar",
    "notif.none": "Inga nya notiser.",
    "account.signedInAs": "Inloggad som {email}",
    "account.settings": "Inställningar",
    "account.signOut": "Logga ut",
    "account.signOutDone": "Utloggad — lokalt läge",
    "account.signIn": "Logga in / skapa konto",

    "settings.language": "Språk",
    "settings.langUpdated": "Språk uppdaterat",
    "common.loading": "Laddar…",
    "common.error": "Något gick fel",
    "common.backToMenu": "Tillbaka till menyn",

    // ---- home page ----
    "greeting.morning": "God morgon",
    "greeting.afternoon": "God eftermiddag",
    "greeting.evening": "God kväll",
    "menu.hintLive": "Välj något att plugga på, eller skapa ett nytt set.",
    "menu.hintDemo": "Körs i demoläge — se Inställningar för hur du slår på live-läge.",
    "menu.newSet": "Nytt set",
    "menu.pageTitle": "Meny",

    "dash.noResults": "Inga resultat än",
    "dash.overallMastery": "Total nivå",
    "dash.startStudying": "Börja plugga",
    "dash.heroHintEmpty": "Slutför ett pass så dyker din nivå upp här.",
    "dash.heroHint": "{topics} spårade · {sessions} klara",
    "dash.topic": "1 ämnesområde",
    "dash.topics": "{n} ämnesområden",
    "dash.session": "1 pass",
    "dash.sessions": "{n} pass",
    "dash.dayStreak": "dags streak",
    "dash.daysStreak": "dagars streak",
    "dash.streakEmpty": "Plugga idag för att starta en streak",
    "dash.dueNow": "Dags nu — tryck för att repetera",
    "dash.dueForReview": "Väntar på repetition",

    "today.continue": "Fortsätt där du slutade",
    "today.progress": "{title} · {n} av {total} besvarade",

    "sets.heading": "Dina set",
    "sets.searchPlaceholder": "Sök set…",
    "sets.sortNewest": "Nyast",
    "sets.sortAZ": "A–Ö",
    "sets.sortWeakest": "Svagast",
    "sets.tabAssignments": "Övningar",
    "sets.tabTests": "Prov",
    "sets.assignmentsNoun": "övningar",
    "sets.testsNoun": "prov",
    "sets.chipAll": "Alla",
    "sets.generalSubject": "Allmänt",
    "sets.newAssignment": "Ny övning",
    "sets.newTest": "Nytt prov",
    "sets.inProgress": "Pågående",
    "sets.answeredProgress": "{answered} av {total} besvarade",
    "sets.questionCount": "1 fråga",
    "sets.questionsCount": "{n} frågor",
    "sets.doneTimes": " · klar {n}×",
    "sets.setCount": "1 set",
    "sets.setsCount": "{n} set",
    "sets.noMatch": "Inga {tab} matchar ”{query}”. ",
    "sets.matchSwitch": "{n} {tab} matchar — byt till {target}",

    "empty.libraryTitle": "Ditt bibliotek är tomt",
    "empty.libraryBody": "Börja med färdiga övningar ur biblioteket — eller gör ett eget set från dina anteckningar, en PDF, ett foto eller bara ett ämne.",
    "empty.noAssignments": "Inga övningar än",
    "empty.noTests": "Inga prov än",
    "empty.assignmentBody": "Gör ett från dina anteckningar, en PDF, ett foto eller bara ett ämne.",
    "empty.testBody": "Skapa på samma sätt — markera det bara som ett prov.",
    "empty.openLibrary": "Öppna övningsbiblioteket",
    "empty.tryDemo": "Prova en demo",
    "empty.demoAdded": "Demo-set tillagda",
    "empty.demoFailed": "Kunde inte ladda demo-seten",

    "cardmenu.examMode": "Starta i provläge",
    "cardmenu.rename": "Byt namn",
    "cardmenu.editQuestions": "Redigera frågor",
    "cardmenu.duplicate": "Duplicera",
    "cardmenu.delete": "Ta bort",
    "cardmenu.renamePrompt": "Byt namn på detta set:",
    "cardmenu.renameNeedsName": "Ett set behöver ett namn",
    "cardmenu.renamed": "Namn ändrat",
    "cardmenu.copiedAs": "Kopierat som ”{title}”",
    "cardmenu.deleteConfirm": "Ta bort ”{title}”?{extra}\n\nDetta kan inte ångras.",
    "cardmenu.deleteExtra": "\n\nDetta tar även bort 1 registrerat försök från din historik.",
    "cardmenu.deleteExtraMany": "\n\nDetta tar även bort {n} registrerade försök från din historik.",
    "cardmenu.deleted": "Borttaget",

    "examcard.title": "Nästa prov",
    "examcard.date": "Datum",
    "examcard.about": "Vad handlar det om? (valfritt)",
    "examcard.aboutPlaceholder": "t.ex. Nationellt prov matematik",
    "examcard.save": "Spara",
    "examcard.cancel": "Avbryt",
    "examcard.change": "Ändra",
    "examcard.pickDateFirst": "Välj ett datum först",
    "examcard.past": "Har varit",
    "examcard.today": "Idag",
    "examcard.tomorrow": "Imorgon",
    "examcard.daysLeft": "{n} dagar kvar",

    "tips.heading": "Dagens studietips",
    "tips.0": "Testa dig själv innan du läser om ett kapitel — att aktivt minnas fastnar bättre än att bara läsa igen.",
    "tips.1": "Korta, återkommande pass slår långa plugg-maraton. Kör 25 fokuserade minuter, ta sedan en riktig paus.",
    "tips.2": "Blanda gärna flera ämnen istället för att köra ett i taget — hjärnan lär sig bättre av växling än av att nöta samma sak länge.",
    "tips.3": "Förklara det du just lärt dig högt för dig själv, som om du undervisade någon annan. Kan du inte förklara det enkelt kan du det inte riktigt än.",
    "tips.4": "Plugga det svåraste momentet först, medan du fortfarande är pigg och fokuserad.",
    "tips.5": "Sömn är en del av inlärningen — hjärnan befäster minnen medan du sover, så en sen kvällsrepetition är inte bortkastad.",
    "tips.6": "Gamla fel är guld värt. Gå igenom det du svarade fel på förra gången innan du kör ett nytt set.",
  },
};
